import PageTitle from "../components/page-title";
import LastUpdated from "../components/last-updated";
import NumberedItem from "../components/numbered-item";
import ListItem from "../components/list-item";

const TermsPage = () => {
  return (
    <section className="relative pt-40 w-full">
      <div className="relative w-full max-w-5xl mx-auto">
        <PageTitle>Terms of Use</PageTitle>
        <LastUpdated date="26 October 2025" />
        <NumberedItem number="1.">
          Introduction and Acceptance These Terms of Use ("Terms") constitute a
          binding agreement between you ("you" or "User") and LYNA Cam UK
          Limited ("LYNA Cam," "we," "us," or "our") governing your access to
          and use of our website, mobile application, and related services
          (collectively, the "Service"). By using the Service, you agree to
          these Terms and our Privacy Policy. If you do not agree, you must not
          use the Service.
        </NumberedItem>
        <NumberedItem number="2.">Definitions</NumberedItem>
        <br />
        <ListItem className="text-2xl">
          "Service": LYNA Cam’s website, mobile application, and all associated
          services.
        </ListItem>
        <ListItem className="text-2xl">
          "User Content": Any data, images, text, or other content submitted by
          you through the Service.
        </ListItem>
        <ListItem className="text-2xl">
          "Personal Information": Information relating to an identifiable
          person, as defined under applicable privacy laws.
        </ListItem>
        <NumberedItem number={"3."}>
          Eligibility You must be at least 13 years old (or the minimum legal
          age in your country) to use the Service. If you are under 18, you
          represent that you have permission from a parent or guardian.
        </NumberedItem>
        <NumberedItem number={"4."}>
          Eligibility You must be at least 13 years old (or the minimum legal
          age in your country) to use the Service. If you are under 18, you
          represent that you have permission from a parent or guardian.
        </NumberedItem>
        <NumberedItem number={"5."}>
          Limited License Subject to your compliance with these Terms, we grant
          you a non-exclusive, non-transferable, revocable license to use the
          Service for personal, non-commercial purposes. All rights not
          expressly granted are reserved by LYNA Cam.
        </NumberedItem>
        <NumberedItem number={"6."}>Acceptable Use You may not:</NumberedItem>
        <br />
        <ListItem className="text-2xl">
          Violate any law or third-party rights.
        </ListItem>
        <ListItem className="text-2xl">
          Upload or transmit harmful, harassing, defamatory, or unlawful
          content.
        </ListItem>
        <ListItem className="text-2xl">
          Attempt to gain unauthorized access to the Service.
        </ListItem>
        <ListItem className="text-2xl">
          Reverse-engineer or scrape our software or systems.
        </ListItem>
        <ListItem className="text-2xl">
          Use the Service for any activity that could harm others or LYNA Cam.
        </ListItem>
        <NumberedItem number={"7."}>
          User Content You retain ownership of your User Content. You grant LYNA
          Cam a limited, non-exclusive, royalty-free license to use, reproduce,
          and display your content solely to operate and improve the Service.
          You are responsible for ensuring your content complies with these
          Terms and applicable laws.
        </NumberedItem>
        <NumberedItem number={"8."}>
          Health and AI Disclaimer LYNA Cam is for informational and wellness
          purposes only and does not constitute medical advice. Any insights
          generated by the Service are probabilistic and may not be accurate.
          Consult a qualified healthcare professional for health-related
          decisions.
        </NumberedItem>
        <NumberedItem number={"9."}>
          Payments and Subscriptions Certain features require payment. Prices,
          billing terms, and cancellation policies are outlined at the point of
          purchase. All payments are processed securely through third-party
          providers and are non-refundable except as required by law.
        </NumberedItem>
        <NumberedItem number={"10."}>
          Intellectual Property All LYNA Cam content (excluding User Content) is
          protected by intellectual property laws and is the exclusive property
          of LYNA Cam or its licensors. You may not reproduce, distribute, or
          create derivative works without our express consent.
        </NumberedItem>
        <NumberedItem number={"11."}>
          Privacy Your use of the Service is subject to our Privacy Policy and
          Cookie Policy, which explain how we collect and use your personal
          data. By using the Service, you consent to our data practices in
          accordance with applicable UK data protection laws.
        </NumberedItem>
        <NumberedItem number={"12."}>
          Third-Party Services The Service may link to third-party content or
          services. We are not responsible for their practices, and use of such
          services is at your own risk.
        </NumberedItem>
        <NumberedItem number={"13."}>
          Termination We may suspend or terminate your access to the Service at
          any time, for any reason, with or without notice. Upon termination,
          your license to use the Service ends, and applicable clauses of these
          Terms will survive.
        </NumberedItem>
        <NumberedItem number={"14."}>
          Disclaimers The Service is provided "as is" without warranties of any
          kind. We do not guarantee that the Service will be error-free, secure,
          or uninterrupted. LYNA Cam disclaims any implied warranties to the
          fullest extent permitted by law.
        </NumberedItem>
        <NumberedItem number={"15."}>
          Limitation of Liability To the extent permitted by law, LYNA Cam shall
          not be liable for indirect, incidental, or consequential damages. Our
          maximum liability under these Terms shall not exceed the amount paid
          by you for the Service in the 12 months preceding the claim or £100,
          whichever is greater.
        </NumberedItem>
        <NumberedItem number={"16."}>
          Indemnification You agree to indemnify and hold harmless LYNA Cam from
          any claims or damages arising from your use of the Service, your User
          Content, or violation of these Terms.
        </NumberedItem>
        <NumberedItem number={"17."}>
          Modifications We may modify these Terms at any time. Material changes
          will be communicated via email, in-app notification, or on our
          website. Continued use of the Service after changes indicates
          acceptance.
        </NumberedItem>
        <NumberedItem number={"18."}>
          Governing Law These Terms are governed by the laws of England and
          Wales. Any disputes will be resolved exclusively in the courts of
          England and Wales unless otherwise required by law.
        </NumberedItem>
        <NumberedItem number={"19."}>
          Severability If any provision is found invalid, the remaining
          provisions will remain in full force and effect.
        </NumberedItem>
        <NumberedItem number={"20."}>
          Contact For questions or concerns, contact us at:{" "}
          <span className="underline text-[#0099ff]">hello@lyna.cam</span>
        </NumberedItem>
        <NumberedItem>
          By using LYNA Cam, you confirm you have read, understood, and agreed
          to these Terms.
        </NumberedItem>
        <NumberedItem>
          Disclaimer: LYNA Cam is not a substitute for professional healthcare
          advice. Always consult a healthcare provider regarding any medical
          concerns.
        </NumberedItem>
      </div>
    </section>
  );
};

export default TermsPage;
